site_name: PistonPusher documentation

nav:
    - Introduction: index.md
    - Getting Started: gettingstarted.md
    - Create:
        '01 - Intro': create/create.md
        '02 - Template mode': create/templatemode.md
        '03 - Custom mode': create/custommode.md
        '04 - Adding an armature': create/addarmature.md
        '05 - Adding your own parts/templates': create/addparts.md
    - Features:
        '00 - Set child of constraints': features/addchildof.md
        '01 - Snap selected to active': features/snapseltoactive.md
        '02 - Track to and apply': features/tracktoandapply.md
        '03 - Lock length anchor': features/locklengthanchor.md
        '04 - Reset hooks': features/resethooks.md
        '05 - Toggle subd modifiers': features/togglesubd.md
        '06 - Remove constraints': features/removeconstraints.md
        '07 - Linked duplicate radial array': features/lnkdupliradarray.md
        '08 - Multi place': features/multiplace.md
        '09 - Delete piston': features/deletepiston.md
        '10 - Collection overlay': features/collectionoverlay.md
        '11 - Select tool': features/selecttool.md
        '12 - Collection/object management': features/collectionmanagement.md
        

theme: readthedocs


