site_name: PistonPusher documentation
site_url: https://pp-docs.readthedocs.io/en/latest/


nav:
    - Introduction: index.md
    - Getting Started: gettingstarted.md
    - Preferences: preferences.md
    - Other addons: oaddons.md
    - Create:
        - Intro: Create/create.md
        - Template mode: Create/templatemode.md
        - Custom mode: Create/custommode.md
        - The length anchor: Create/lengthanchor.md
        - Adding an armature: Create/addarmature.md
        - Adding your own parts/templates: Create/addparts.md
        - Create a piston: Create/createapiston.md
    - Features:
        - Piston snap tool: Features/pistonsnaptool.md
        - Set child of constraints: Features/addchildof.md
        - Set bone as parent tool: Features/setbparent.md
        - Snap selected to active: Features/snapseltoactive.md
        - Track to and apply: Features/tracktoandapply.md
        - Lock length anchor: Features/locklengthanchor.md
        - Reset hooks: Features/resethooks.md
        - Toggle subd modifiers: Features/togglesubd.md
        - Remove constraints: Features/removeconstraints.md
        - Linked duplicate radial array: Features/lnkdupliradarray.md
        - Multi place: Features/multiplace.md
        - Delete piston: Features/deletepiston.md
        - Collection overlay: Features/collectionoverlay.md
        - Select tool: Features/selecttool.md
        - Collection/object management: Features/collectionmanagement.md
    
        

theme: readthedocs



