site_name: PistonPusher documentation
site_url: https://pp-docs.readthedocs.io/en/latest/


nav:
    - Introduction: index.md
    - Getting Started: gettingstarted.md
    - Create:
        Intro: create.md
        Template mode: templatemode.md
        Custom mode: custommode.md
        Adding an armature: addarmature.md
        Adding your own parts/templates: addparts.md
    - Features:
        Set child of constraints: addchildof.md
        Snap selected to active: snapseltoactive.md
        Track to and apply: tracktoandapply.md
        Lock length anchor: locklengthanchor.md
        Reset hooks: resethooks.md
        Toggle subd modifiers: togglesubd.md
        Remove constraints: removeconstraints.md
        Linked duplicate radial array: lnkdupliradarray.md
        Multi place: multiplace.md
        Delete piston: deletepiston.md
        Collection overlay: collectionoverlay.md
        Select tool: selecttool.md
        Collection/object management: collectionmanagement.md
        

theme: readthedocs



